@startuml 実習問題2_1
    actor ユーザー as a
    boundary ブラウザ as b
    control web.php as c
    control jissyu4_1Cntroller as d
    boundary input.blade.php as e
    boundary output.jissyu.blade.php as f

    a -> b: 該当ページをリクエスト[/jissyu6]
    b -> c: GET[/jissyu6]
    c -> d: @index
    d -> e
    a -> e: 送信ボタンを押下
    e -> c: POST
    c -> d: @post

    alt 成功
    d -> f
    else エラー発生
    d -> e
    end

@enduml